DROP TABLE IF EXISTS votos;
DROP TABLE IF EXISTS sessoes;
DROP TABLE IF EXISTS pautas;

CREATE TABLE pautas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    tempo_votacao_minutos BIGINT NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX uk_pauta_titulo_lower ON pautas (LOWER(titulo));

CREATE TABLE sessoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id BIGINT NOT NULL,
    started_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_sessao_pauta FOREIGN KEY (pauta_id) REFERENCES pautas(id)
);

CREATE UNIQUE INDEX uk_sessao_pauta ON sessoes (pauta_id);

CREATE TABLE votos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id BIGINT NOT NULL,
    documento VARCHAR(14) NOT NULL,
    escolha_voto VARCHAR(10) NOT NULL,
    CONSTRAINT fk_voto_sessao FOREIGN KEY (sessao_id) REFERENCES sessoes(id),
    CONSTRAINT uk_voto_sessao_documento UNIQUE (sessao_id, documento)
);

CREATE INDEX idx_voto_sessao_escolha ON votos (sessao_id, escolha_voto);