spring.application.name=votacao-sdui
spring.main.banner-mode=off

spring.jackson.property-naming-strategy=SNAKE_CASE

spring.datasource.url=jdbc:h2:mem:votacao
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

app.documento-validator.base-url=https://httpbin.org
app.documento-validator.connect-timeout-ms=500
app.documento-validator.read-timeout-ms=500

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.client-id=votacao-sdui
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
