spring.application.name=votacao-sdui

spring.datasource.url=jdbc:h2:mem:votacao
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Criar/atualizar tabelas automaticamente com base nas entidades
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.h2.console.enabled=true
