spring.application.name=votacao-sdui

spring.jackson.property-naming-strategy=SNAKE_CASE

spring.datasource.url=jdbc:h2:mem:votacao
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

app.documento-validator.base-url=https://httpbin.org
app.documento-validator.connect-timeout-ms=500
app.documento-validator.read-timeout-ms=500
