DROP TABLE IF EXISTS votos;
DROP TABLE IF EXISTS sessoes;
DROP TABLE IF EXISTS pautas;

CREATE TABLE pautas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    tempo_votacao_minutos BIGINT NOT NULL DEFAULT 1,
    titulo_normalizado VARCHAR(150) GENERATED ALWAYS AS (LOWER(titulo)),
    CONSTRAINT uk_pauta_titulo_lower UNIQUE (titulo_normalizado)
);

CREATE TABLE sessoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pauta BIGINT NOT NULL,
    started_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_sessao_pauta FOREIGN KEY (id_pauta) REFERENCES pautas(id)
);

CREATE UNIQUE INDEX uk_sessao_pauta ON sessoes (id_pauta);

CREATE TABLE votos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sessao_id BIGINT NOT NULL,
    documento VARCHAR(14) NOT NULL,
    escolha_voto VARCHAR(10) NOT NULL,
    CONSTRAINT fk_voto_sessao FOREIGN KEY (sessao_id) REFERENCES sessoes(id),
    CONSTRAINT uk_voto_sessao_documento UNIQUE (sessao_id, documento)
);

CREATE INDEX idx_voto_sessao_escolha ON votos (sessao_id, escolha_voto);
