spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.h2.console.enabled=false
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

logging.level.root=WARN
logging.level.com.votacao=INFO
